services:
  django_app:
    container_name: web_app
    build: .
    env_file:
      - ./.env
    command: sh -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --no-input
      && python manage.py loaddata fix.json
      && gunicorn --workers=2 --bind 0.0.0.0:8000 LynxWasp.wsgi --reload"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - web_db
    networks:
      - django_network
  web_db:
    container_name: db_app
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file:
      - ./.env
    networks:
      - django_network
volumes:
  postgres_data:
networks:
  django_network: