version: "3.8"
services:
  django_app:
    container_name: web_app
    build: .
    env_file:
      - ./.env
    command: sh -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata fix.json
      && gunicorn --workers=2 --bind 0.0.0.0:8000 LynxWasp.wsgi"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - web_db
  web_db:
    container_name: db_app
    image: postgres:15-alpine
    env_file:
      - ./.env
