[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 120
[flake8]
max-line-length = 120

[tool.pycln]
all = true
expand-stars = true
exclude= "(.eggs|.git|.mypy_cache|__pycache__|__init__.py)"

