<<<<<<< HEAD:product_manager_ices/migrations/0002_order_worker_owner.py
# Generated by Django 2.2.3 on 2019-11-01 16:55
=======
# Generated by Django 2.2.3 on 2019-11-01 13:27
>>>>>>> features:product_manager_ices/migrations/0002_order_worker_owner.py

from django.conf import settings
from django.db import migrations, models
import product_manager_ices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_manager_ices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker_owner',
            field=models.ForeignKey(null=True, on_delete=models.SET(product_manager_ices.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
