# Generated by Django 2.2.3 on 2019-08-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ices',
            name='flavour_type',
        ),
    ]
