# Generated by Django 2.2.3 on 2019-11-06 19:09

from django.conf import settings
from django.db import migrations, models
import product_manager_ices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_manager_ices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker_owner',
            field=models.ForeignKey(null=True, on_delete=models.SET(product_manager_ices.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
