# Generated by Django 2.2.3 on 2019-12-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0002_order_worker_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
