# Generated by Django 2.2.3 on 2019-11-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0002_order_worker_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ices_ordered',
            field=models.ManyToManyField(related_name='order_ice', to='product_manager_ices.OrderItem'),
        ),
    ]
