# Generated by Django 2.2.3 on 2019-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0002_remove_ices_flavour_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='flavour',
        ),
        migrations.AddField(
            model_name='ices',
            name='flavour_type',
            field=models.ManyToManyField(to='product_manager_ices.Flavour'),
        ),
    ]
