# Generated by Django 2.2.3 on 2019-09-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0002_ices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager_ices.Ices')),
            ],
        ),
    ]
