# Generated by Django 2.2.3 on 2019-08-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='worker_owner',
        ),
    ]
