# Generated by Django 4.1.7 on 2023-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0002_order_worker_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Started'), (2, 'Waiting'), (3, 'Finished')], default=1),
        ),
    ]
