# Generated by Django 2.2.3 on 2019-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0003_auto_20190820_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ices',
            name='flavour_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flavour',
            field=models.ManyToManyField(to='product_manager_ices.Flavour'),
        ),
    ]
