# Generated by Django 4.1.7 on 2023-11-14 14:37

from django.db import migrations
import product_manager_ices.fields


class Migration(migrations.Migration):

    replaces = [('product_manager_ices', '0004_alter_flavour_flavour_alter_ices_type'), ('product_manager_ices', '0005_alter_flavour_flavour_alter_ices_type')]

    dependencies = [
        ('product_manager_ices', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=product_manager_ices.fields.TypeField(max_length=45),
        ),
        migrations.AlterField(
            model_name='ices',
            name='type',
            field=product_manager_ices.fields.TypeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=product_manager_ices.fields.TypeField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='ices',
            name='type',
            field=product_manager_ices.fields.TypeField(max_length=50, unique=True),
        ),
    ]
