# Generated by Django 2.2.3 on 2019-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0003_auto_20191102_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ices_ordered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(related_name='parentorder', to='product_manager_ices.Order'),
        ),
    ]
