# Generated by Django 4.1.7 on 2023-09-21 11:23

from django.db import migrations
import product_manager_ices.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=product_manager_ices.fields.TypeField(max_length=45),
        ),
        migrations.AlterField(
            model_name='ices',
            name='type',
            field=product_manager_ices.fields.TypeField(max_length=50),
        ),
    ]
