# Generated by Django 2.2.3 on 2019-09-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_manager_ices', '0003_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sell', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('ices_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager_ices.OrderItem')),
                ('worker_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
