# Generated by Django 4.1.7 on 2023-11-09 14:37

from django.db import migrations
import product_manager_ices.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0004_alter_flavour_flavour_alter_ices_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=product_manager_ices.fields.TypeField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='ices',
            name='type',
            field=product_manager_ices.fields.TypeField(max_length=50, unique=True),
        ),
    ]
