# Generated by Django 2.2.3 on 2019-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0004_auto_20191103_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(related_name='orderitem', to='product_manager_ices.Order'),
        ),
    ]
