# Generated by Django 2.2.3 on 2019-09-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ices',
            name='flavour',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flavour',
            field=models.ManyToManyField(to='product_manager_ices.Flavour'),
        ),
    ]
