# Generated by Django 2.2.3 on 2019-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0005_auto_20190902_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ices_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='ices_ordered',
            field=models.ManyToManyField(to='product_manager_ices.OrderItem'),
        ),
    ]
