# Generated by Django 4.1.7 on 2023-11-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0004_alter_flavour_flavour_alter_ices_type_squashed_0005_alter_flavour_flavour_alter_ices_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='product_manager_ices.order'),
        ),
    ]
