# Generated by Django 2.2.3 on 2019-09-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0006_auto_20190902_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='finished',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Started'), ('2', 'Waiting'), ('3', 'Finished')], default='1', max_length=9),
        ),
    ]
