# Generated by Django 4.1.7 on 2023-11-15 15:44

from django.conf import settings
from django.db import migrations, models
import product_manager_ices.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_manager_ices', '0006_remove_orderitem_order_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='worker_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(product_manager_ices.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
