# Generated by Django 2.2.3 on 2019-10-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0007_auto_20190907_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Started'), (2, 'Waiting'), (3, 'Finished')], default=1, max_length=9),
        ),
    ]
