# Generated by Django 4.1.7 on 2023-11-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0007_alter_order_worker_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='product_manager_ices.order'),
        ),
    ]
