# Generated by Django 2.2.3 on 2019-10-07 18:49

from django.conf import settings
from django.db import migrations, models
import product_manager_ices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_ices', '0008_auto_20191001_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='worker_owner',
            field=models.ForeignKey(null=True, on_delete=models.SET(product_manager_ices.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
